# Generated by Django 4.1 on 2023-11-10 19:57

from django.db import migrations, models
import django.db.models.deletion
import polls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserStatus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', polls.CompositeAutoField(db_index=True, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('customer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='polls.userstatus')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
